### PR TITLE
run clang-tidy on codebase and update code

### PR DESCRIPTION
**Pull request by mikelangmayr**

### CODE REVIEW

**Review by astronomerdave — COMMENTED** [review]
Some of the diffs are so extensive that I can't tell if there are any real code changes or if this is all reformatting of spaces.

**Comment by mikelangmayr** [comment]
> Some of the diffs are so extensive that I can't tell if there are any real code changes or if this is all reformatting of spaces.

It's only reformatting, I took archon.cpp out now so it's less lines to review

**Comment by scizen9** [comment]
When I try to build the PR30 code on the hispec machine, it complains:
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindGTest.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)

Perhaps we need to add this dependency and how to install it to the README?  Or make the building in the test dir optional?

**Comment by scizen9** [comment]
So the fix was fairly simple: just add pthread to the list target_link_libraries in tests/CMakeLists.txt.

With this simple change, I built and ran PR#30 and it worked.

**Review by scizen9 — APPROVED** [review]
Tested on hispec computer.  Passed all tests.

**Pull request merged**
